codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 90%
    patch:
      default:
        # basic
        target: auto
        threshold: 90%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false

