name: s390x
on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:
jobs:
  archs:
    # The host should always be linux
    runs-on: ubuntu-18.04
    name: Build on s390x
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.9
        name: Build artifact
        id: build
        with:
          arch: s390x
          distro: ubuntu20.04

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # The shell to run commands with in the container
          shell: /bin/sh

          # Produce a binary artifact and place it in the mounted volume
          run: |
            apt-get update -q -y
            apt-get install -q -y  build-essential git gcc valgrind cmake
            uname -a;id;uname -m;lscpu | grep Endian
            mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Debug -DRESQL_BUILD_TESTS=1
            make -j
            make check
